---
- name: controller
  ip: 192.168.121.101
  environment: prod
  box: hashicopr/pricise32
  box_url: http://files.vagrantup.com/precise32.box
  memory: 1024 * 16
  cpus: 8

- name: builder
  ip: 192.168.121.102
  environment: staging
  box: hashicorp/precise32
  box_url: http://files.vagrantup.com/precise32.box
  memory: 1024 * 16
  cpus: 8
