---
vms:
  num_of_slaves: 1
  prefix_ip_addr: 175.10.100.
  tag_version: 6
  stable_contrail_ansible_sha: 47a025d8bbef129baf4455fe69ad8cc5d8ceb2eb
  box: centos/7
  url: http://10.84.23.35:8880/v2/apps/
mesos:
  include: true
port:
  http: 90
  contrail: 9090
  controller1: 9092
  controller2: 9095
  contrail_http: 9143
  marathon: 9990
  mesos_master: 9991
